### ISSUE TITLE
Backspace sound

### ISSUE THREAD

**Issue by fobuss** [deimusmeister/ArmenianKeyboard#1]
**Steps to reproduce:**
Open Application
Enable sounds
Open Messages
Choose contact and start conversation
Click and hold _backspace_ button

**Result:**
When user is clicking and holding _backspace_ button, beeping not one time like all other languages, but beeping many times, still user is holding button.

**Comment by deimusmeister** [comment]
Holding backspace triggers multiple beeps also on system keyboard
