### ISSUE TITLE
Capital letter issue

### ISSUE THREAD

**Issue by fobuss** [deimusmeister/ArmenianKeyboard#2]
**Steps to reproduce:**

Open Application
Open Messages
Choose contact and start conversation
Set keyboard to _Armenian keyboard_
First letter is capital letter
Type some text
Delete text

**Result:**
When user is deleting text and wanted to start typing text, first letter is not capital letter.
On _English_, _Russian_ languages capital letter is saving state.

**Comment by deimusmeister** [comment]
Fixed.
Is released with version 2.5
